apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    # Root route - all alerts start here
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'default-receiver'
      routes:
      # Critical alerts route
      - match:
          severity: critical
        receiver: 'critical-alerts'
        group_wait: 5s
        group_interval: 2m
        repeat_interval: 1h

      # Warning alerts route
      - match:
          severity: warning
        receiver: 'warning-alerts'
        group_wait: 30s
        group_interval: 10m
        repeat_interval: 4h

      # Service down alerts
      - match:
          alertname: ServiceDown
        receiver: 'service-alerts'
        group_wait: 5s
        repeat_interval: 30m

      # Instance down alerts
      - match:
          alertname: InstanceDown
        receiver: 'infrastructure-alerts'
        group_wait: 5s
        repeat_interval: 30m

    receivers:
    # Default receiver - no notifications
    - name: 'default-receiver'

    # Critical alerts receiver - no notifications
    - name: 'critical-alerts'

    # Warning alerts receiver - no notifications
    - name: 'warning-alerts'

    # Service-specific alerts - no notifications
    - name: 'service-alerts'

    # Infrastructure alerts - no notifications
    - name: 'infrastructure-alerts'

    # Inhibit rules - suppress less critical alerts when more critical ones are firing
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster', 'service']

    - source_match:
        alertname: 'InstanceDown'
      target_match_re:
        alertname: '(HighCpuUsage|HighMemoryUsage|DiskSpaceLow)'
      equal: ['instance']

    # Templates for custom message formatting
    templates:
    - '/etc/alertmanager/templates/*.tmpl'
