apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: bench 
spec:
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30800
  type: NodePort
